FROM openjdk:8 
EXPOSE 8091
ADD target/velotn-MicroService_association-0.0.1-SNAPSHOT-exec.jar velotn-MicroService_association-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "velotn-MicroService_association-0.0.1-SNAPSHOT.jar"]